let client_profile = require('../models/clientProfile');

let client_profile_controller = { // the name of the client should be saved in a session to use it to save  pictures or video uploaded by the client

        createClientProfile:function(req, res){

            res.render('createClientProfile');

            ///////
            // add clientInfo, paymentInfo and any other data to the database.
            // view has not been implemented yet.
            ///////

        },

        uploadClientPicture:function(req, res){ // stores the name of the client which is unique and the name of the picture which is also unique in the database

      if(req.file == null){
        console.log("there is no picture chosen!");
      }else{
        var mime_type = req.file.mimetype;                      // mime_type contains the type of file with extension, for images it contains 'image/png' the extension might change
        var check_type = mime_type.substr(0,5);                 // check_type substring the first five letters which is an image if the file is a image

        if(check_type != 'image'){
          console.log("not image!");
          console.log(mime_type);
        }
        else {
        console.log(mime_type);
        var picture_name = req.file.filename;                 // the filename is generated by multer and it's unique

        /////////
        // add to picture name and client name database
        ////////
        }
      }


        },

        uploadClientVideo:function(req, res){   // stores the name of the client which is unique and the name of the video which is also unique in the database

      if(req.file == null){
        console.log("there is no video chosen!");
      }else{
        var mime_type = req.file.mimetype;               // mime_type contains the type of file with extension, for videos it contains 'video/mp4' the extension might change
        var check_type = mime_type.substr(0,5);         // check_type substring the first five letters which is a video if the file is a video

        if(check_type != 'video'){
          console.log("not video!");
          console.log(mime_type);
        }
        else {
        console.log(mime_type);
        var video_name = req.file.filename;           // the filename is generated by multer and it's unique

        /////////
        // add to video name and client name database
        ////////
        }
      }

        }



}

module.exports = client_profile_controller;
